# Generated by Django 4.2.5 on 2023-09-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=60)),
                ('whatsapp', models.CharField(max_length=50)),
                ('telegram', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
            ],
        ),
    ]
